import { GraphQLResolveInfo } from 'graphql';
import { CommentableInterface, Comment, Entry, Day, Report, Trainer, Trainee, UserInterface } from './models';
import { Context } from './context';
export type Maybe<T> = T | undefined;
export type InputMaybe<T> = T | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export type RequireFields<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
};

export type GqlAdmin = GqlUserInterface & {
  __typename?: 'Admin';
  alexaSkillLinked?: Maybe<Scalars['Boolean']['output']>;
  avatar: Scalars['String']['output'];
  createdAt: Scalars['String']['output'];
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  language?: Maybe<Scalars['String']['output']>;
  lastName: Scalars['String']['output'];
  notification?: Maybe<Scalars['Boolean']['output']>;
  signature?: Maybe<Scalars['String']['output']>;
  theme?: Maybe<Scalars['String']['output']>;
  type: GqlUserTypeEnum;
  username: Scalars['String']['output'];
};

export type GqlComment = {
  __typename?: 'Comment';
  createdAt: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  text?: Maybe<Scalars['String']['output']>;
  user: GqlUserInterface;
};

/** An object that can have comments */
export type GqlCommentableInterface = {
  comments: Array<GqlComment>;
  id: Scalars['ID']['output'];
};

export type GqlCompany = {
  __typename?: 'Company';
  id: Scalars['String']['output'];
  logo: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type GqlCreateCommentPayload = {
  __typename?: 'CreateCommentPayload';
  comment: GqlComment;
  commentable: GqlCommentableInterface;
};

export type GqlCreateTraineeInput = {
  companyId: Scalars['String']['input'];
  email: Scalars['String']['input'];
  endDate: Scalars['String']['input'];
  firstName: Scalars['String']['input'];
  lastName: Scalars['String']['input'];
  startDate: Scalars['String']['input'];
  startOfToolUsage: Scalars['String']['input'];
};

export type GqlCreateTrainerInput = {
  email: Scalars['String']['input'];
  firstName: Scalars['String']['input'];
  lastName: Scalars['String']['input'];
};

export type GqlDay = GqlCommentableInterface & {
  __typename?: 'Day';
  comments: Array<GqlComment>;
  createdAt: Scalars['String']['output'];
  date: Scalars['String']['output'];
  entries: Array<GqlEntry>;
  id: Scalars['ID']['output'];
  status?: Maybe<GqlDayStatusEnum>;
};

export type GqlDayStatusEnum =
  /** school/university */
  | 'education'
  /** public holiday */
  | 'holiday'
  /** sick leave */
  | 'sick'
  /** vacation */
  | 'vacation'
  /** workday */
  | 'work';

/** Autogenerated return type of DevSetUser */
export type GqlDevSetUserPayload = {
  __typename?: 'DevSetUserPayload';
  user?: Maybe<GqlUserInterface>;
};

export type GqlEntry = GqlCommentableInterface & {
  __typename?: 'Entry';
  comments: Array<GqlComment>;
  createdAt: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  orderId: Scalars['Int']['output'];
  text: Scalars['String']['output'];
  time: Scalars['Int']['output'];
};

export type GqlEntryInput = {
  text: Scalars['String']['input'];
  time: Scalars['Int']['input'];
};

export type GqlLaraConfig = {
  __typename?: 'LaraConfig';
  expectedWorkDayMinutes: Scalars['Int']['output'];
  finishedWeekDayCount: Scalars['Int']['output'];
  maxEducationDayMinutes: Scalars['Int']['output'];
  maxEntryMinutes: Scalars['Int']['output'];
  maxPeriodYearsCount: Scalars['Int']['output'];
  maxWorkDayMinutes: Scalars['Int']['output'];
  minEducationDayMinutes: Scalars['Int']['output'];
  minWorkDayMinutes: Scalars['Int']['output'];
};

export type GqlMutateEntryPayload = {
  __typename?: 'MutateEntryPayload';
  day: GqlDay;
  entry?: Maybe<GqlEntry>;
  report: GqlReport;
};

export type GqlMutation = {
  __typename?: 'Mutation';
  /** [DEV] Login as a user. */
  _devloginuser?: Maybe<GqlOAuthPayload>;
  /** [DEV] Sets the users type. */
  _devsetusertype: GqlDevSetUserPayload;
  /** Claims a Trainee by the current Trainer */
  claimTrainee?: Maybe<GqlTrainerTraineePayload>;
  /** Creates a new comment on a Day which is identified by the id argument. */
  createCommentOnDay: GqlCreateCommentPayload;
  /** Creates a new comment on a Entry which is identified by the id argument. */
  createCommentOnEntry: GqlCreateCommentPayload;
  /** Creates a new comment on a Report which is identified by the id argument. */
  createCommentOnReport: GqlCreateCommentPayload;
  /** Creates a new entry which is assigned to the matching report based on the day Id */
  createEntry: GqlMutateEntryPayload;
  /** Create OAuth Code */
  createOAuthCode: Scalars['String']['output'];
  /** Creates Trainee. */
  createTrainee?: Maybe<GqlTrainee>;
  /** Creates Trainer. */
  createTrainer?: Maybe<GqlTrainer>;
  /** Deletes an entry by the given ID. Only considers entries made by the current user. Returns the ID of the deleted entry. */
  deleteEntry: GqlMutateEntryPayload;
  /** Link Alexa account */
  linkAlexa?: Maybe<GqlUserInterface>;
  /** Login via microsoft */
  login?: Maybe<GqlOAuthPayload>;
  /** Marks User to be deleted */
  markUserForDeletion?: Maybe<GqlUserInterface>;
  /** Unclaims a Trainee by the current Trainer */
  unclaimTrainee?: Maybe<GqlTrainerTraineePayload>;
  /** Unlink Alexa account */
  unlinkAlexa?: Maybe<GqlUserInterface>;
  /** Unmarks User from deletion */
  unmarkUserForDeletion?: Maybe<GqlUserInterface>;
  /** Updates the current trainee */
  updateCurrentTrainee?: Maybe<GqlTrainee>;
  /** Updates the current user */
  updateCurrentUser?: Maybe<GqlUserInterface>;
  /** Updates day which is identified by the id argument. */
  updateDay?: Maybe<GqlDay>;
  updateEntry: GqlMutateEntryPayload;
  updateEntryOrder: GqlMutateEntryPayload;
  /** Updates report which is identified by the id argument. */
  updateReport?: Maybe<GqlUpdateReportPayload>;
  /** Updates Trainee. */
  updateTrainee?: Maybe<GqlTrainee>;
  /** Updates Trainer. */
  updateTrainer?: Maybe<GqlTrainer>;
};


export type GqlMutation_DevloginuserArgs = {
  id: Scalars['String']['input'];
};


export type GqlMutation_DevsetusertypeArgs = {
  type: Scalars['String']['input'];
};


export type GqlMutationClaimTraineeArgs = {
  id: Scalars['ID']['input'];
};


export type GqlMutationCreateCommentOnDayArgs = {
  id: Scalars['ID']['input'];
  text: Scalars['String']['input'];
  traineeId: Scalars['ID']['input'];
};


export type GqlMutationCreateCommentOnEntryArgs = {
  id: Scalars['ID']['input'];
  text: Scalars['String']['input'];
  traineeId: Scalars['ID']['input'];
};


export type GqlMutationCreateCommentOnReportArgs = {
  id: Scalars['ID']['input'];
  text: Scalars['String']['input'];
  traineeId: Scalars['ID']['input'];
};


export type GqlMutationCreateEntryArgs = {
  dayId: Scalars['String']['input'];
  input: GqlEntryInput;
};


export type GqlMutationCreateTraineeArgs = {
  input: GqlCreateTraineeInput;
};


export type GqlMutationCreateTrainerArgs = {
  input: GqlCreateTrainerInput;
};


export type GqlMutationDeleteEntryArgs = {
  id: Scalars['ID']['input'];
};


export type GqlMutationLinkAlexaArgs = {
  code: Scalars['String']['input'];
  state: Scalars['String']['input'];
};


export type GqlMutationLoginArgs = {
  email: Scalars['String']['input'];
};


export type GqlMutationMarkUserForDeletionArgs = {
  id: Scalars['ID']['input'];
};


export type GqlMutationUnclaimTraineeArgs = {
  id: Scalars['ID']['input'];
};


export type GqlMutationUnmarkUserForDeletionArgs = {
  id: Scalars['ID']['input'];
};


export type GqlMutationUpdateCurrentTraineeArgs = {
  input: GqlUpdateCurrentTraineeInput;
};


export type GqlMutationUpdateCurrentUserArgs = {
  input?: InputMaybe<GqlUserInput>;
};


export type GqlMutationUpdateDayArgs = {
  id: Scalars['ID']['input'];
  status?: InputMaybe<Scalars['String']['input']>;
};


export type GqlMutationUpdateEntryArgs = {
  id: Scalars['ID']['input'];
  input: GqlEntryInput;
};


export type GqlMutationUpdateEntryOrderArgs = {
  dayId: Scalars['ID']['input'];
  entryId: Scalars['ID']['input'];
  orderId: Scalars['Int']['input'];
};


export type GqlMutationUpdateReportArgs = {
  department?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  status?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
};


export type GqlMutationUpdateTraineeArgs = {
  id: Scalars['ID']['input'];
  input: GqlUpdateTraineeInput;
};


export type GqlMutationUpdateTrainerArgs = {
  id: Scalars['ID']['input'];
  input: GqlUpdateTrainerInput;
};

export type GqlOAuthPayload = {
  __typename?: 'OAuthPayload';
  accessToken: Scalars['String']['output'];
  expiresIn: Scalars['Int']['output'];
  refreshToken?: Maybe<Scalars['String']['output']>;
};

export type GqlPrintPayload = {
  __typename?: 'PrintPayload';
  estimatedWaitingTime: Scalars['Int']['output'];
};

export type GqlQuery = {
  __typename?: 'Query';
  /** Get the alexa account linking url */
  alexaLinkingUrl?: Maybe<Scalars['String']['output']>;
  /** Will look for Users to delete */
  cleanup: Scalars['Boolean']['output'];
  companies?: Maybe<Array<GqlCompany>>;
  config: GqlLaraConfig;
  /** Returns the logged in user. This user can be either a Trainee or a Trainer. */
  currentUser?: Maybe<GqlUserInterface>;
  /** Get a User by ID */
  getUser?: Maybe<GqlUserInterface>;
  /** Print single report or report batch */
  print: GqlPrintPayload;
  /** Finds the report for a specifig trainee on the requested year and week. */
  reportForTrainee?: Maybe<GqlReport>;
  /** Finds the report for the requested year and week. */
  reportForYearAndWeek?: Maybe<GqlReport>;
  /** Get all Reports for the current User. The result can be filtered by the 'statuses' attribut */
  reports: Array<Maybe<GqlReport>>;
  /** Get all Suggestions */
  suggestions: Array<GqlSuggestion>;
  /** Get all Trainees */
  trainees: Array<GqlTrainee>;
  /** Get all Trainers */
  trainers: Array<GqlTrainer>;
};


export type GqlQueryGetUserArgs = {
  id: Scalars['ID']['input'];
};


export type GqlQueryPrintArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type GqlQueryReportForTraineeArgs = {
  id: Scalars['ID']['input'];
  week: Scalars['Int']['input'];
  year: Scalars['Int']['input'];
};


export type GqlQueryReportForYearAndWeekArgs = {
  week: Scalars['Int']['input'];
  year: Scalars['Int']['input'];
};


export type GqlQueryReportsArgs = {
  statuses?: InputMaybe<Array<GqlReportStatus>>;
};

export type GqlReport = GqlCommentableInterface & {
  __typename?: 'Report';
  comments: Array<GqlComment>;
  createdAt: Scalars['String']['output'];
  days: Array<GqlDay>;
  department?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  nextReportLink?: Maybe<Scalars['String']['output']>;
  previousReportLink?: Maybe<Scalars['String']['output']>;
  reportAccepted?: Maybe<Scalars['String']['output']>;
  status: GqlReportStatus;
  summary?: Maybe<Scalars['String']['output']>;
  week: Scalars['Int']['output'];
  year: Scalars['Int']['output'];
};

/** Represents the current state of the report */
export type GqlReportStatus =
  /** Done reports are marked as archived */
  | 'archived'
  /** Used if there is any problem with a report */
  | 'reopened'
  /** Passes the report to the trainer */
  | 'review'
  /** Report is open */
  | 'todo';

export type GqlSuggestion = {
  __typename?: 'Suggestion';
  text: Scalars['String']['output'];
  time: Scalars['String']['output'];
};

export type GqlTrainee = GqlUserInterface & {
  __typename?: 'Trainee';
  alexaSkillLinked?: Maybe<Scalars['Boolean']['output']>;
  /** The url for the users avatar image. */
  avatar: Scalars['String']['output'];
  company: GqlCompany;
  course?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['String']['output'];
  deleteAt?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  endOfToolUsage?: Maybe<Scalars['String']['output']>;
  firstName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  language?: Maybe<Scalars['String']['output']>;
  lastName: Scalars['String']['output'];
  notification?: Maybe<Scalars['Boolean']['output']>;
  openReportsCount: Scalars['Int']['output'];
  reports: Array<GqlReport>;
  signature?: Maybe<Scalars['String']['output']>;
  startDate?: Maybe<Scalars['String']['output']>;
  startOfToolUsage?: Maybe<Scalars['String']['output']>;
  theme?: Maybe<Scalars['String']['output']>;
  trainer?: Maybe<GqlTrainer>;
  type: GqlUserTypeEnum;
  username: Scalars['String']['output'];
};

export type GqlTrainer = GqlUserInterface & {
  __typename?: 'Trainer';
  alexaSkillLinked?: Maybe<Scalars['Boolean']['output']>;
  avatar: Scalars['String']['output'];
  createdAt: Scalars['String']['output'];
  deleteAt?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  language?: Maybe<Scalars['String']['output']>;
  lastName: Scalars['String']['output'];
  notification?: Maybe<Scalars['Boolean']['output']>;
  signature?: Maybe<Scalars['String']['output']>;
  theme?: Maybe<Scalars['String']['output']>;
  trainees: Array<GqlTrainee>;
  type: GqlUserTypeEnum;
  username: Scalars['String']['output'];
};

export type GqlTrainerTraineePayload = {
  __typename?: 'TrainerTraineePayload';
  trainee: GqlTrainee;
  trainer: GqlTrainer;
};

export type GqlUpdateCurrentTraineeInput = {
  course?: InputMaybe<Scalars['String']['input']>;
};

export type GqlUpdateReportPayload = {
  __typename?: 'UpdateReportPayload';
  report: GqlReport;
  trainee: GqlTrainee;
};

export type GqlUpdateTraineeInput = {
  companyId?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  firstName?: InputMaybe<Scalars['String']['input']>;
  lastName?: InputMaybe<Scalars['String']['input']>;
  startDate?: InputMaybe<Scalars['String']['input']>;
  startOfToolUsage?: InputMaybe<Scalars['String']['input']>;
};

export type GqlUpdateTrainerInput = {
  email?: InputMaybe<Scalars['String']['input']>;
  firstName?: InputMaybe<Scalars['String']['input']>;
  lastName?: InputMaybe<Scalars['String']['input']>;
};

export type GqlUserInput = {
  language?: InputMaybe<Scalars['String']['input']>;
  notification?: InputMaybe<Scalars['Boolean']['input']>;
  signature?: InputMaybe<Scalars['String']['input']>;
  theme?: InputMaybe<Scalars['String']['input']>;
};

export type GqlUserInterface = {
  alexaSkillLinked?: Maybe<Scalars['Boolean']['output']>;
  avatar: Scalars['String']['output'];
  createdAt: Scalars['String']['output'];
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  language?: Maybe<Scalars['String']['output']>;
  lastName: Scalars['String']['output'];
  notification?: Maybe<Scalars['Boolean']['output']>;
  signature?: Maybe<Scalars['String']['output']>;
  theme?: Maybe<Scalars['String']['output']>;
  type: GqlUserTypeEnum;
  username: Scalars['String']['output'];
};

export type GqlUserTypeEnum =
  /** User is an Admin */
  | 'Admin'
  /** User is a Trainee */
  | 'Trainee'
  /** User is a Trainer */
  | 'Trainer';

export type WithIndex<TObject> = TObject & Record<string, any>;
export type ResolversObject<TObject> = WithIndex<TObject>;

export type ResolverTypeWrapper<T> = Promise<T> | T;


export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> = ResolverFn<TResult, TParent, TContext, TArgs> | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = {}, TContext = {}> = (obj: T, context: TContext, info: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;



/** Mapping between all available schema types and the resolvers types */
export type GqlResolversTypes = ResolversObject<{
  Admin: ResolverTypeWrapper<GqlAdmin>;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
  Comment: ResolverTypeWrapper<Comment>;
  CommentableInterface: ResolverTypeWrapper<CommentableInterface>;
  Company: ResolverTypeWrapper<GqlCompany>;
  CreateCommentPayload: ResolverTypeWrapper<Omit<GqlCreateCommentPayload, 'comment' | 'commentable'> & { comment: GqlResolversTypes['Comment'], commentable: GqlResolversTypes['CommentableInterface'] }>;
  CreateTraineeInput: GqlCreateTraineeInput;
  CreateTrainerInput: GqlCreateTrainerInput;
  Day: ResolverTypeWrapper<Day>;
  DayStatusEnum: GqlDayStatusEnum;
  DevSetUserPayload: ResolverTypeWrapper<Omit<GqlDevSetUserPayload, 'user'> & { user?: Maybe<GqlResolversTypes['UserInterface']> }>;
  Entry: ResolverTypeWrapper<Entry>;
  EntryInput: GqlEntryInput;
  ID: ResolverTypeWrapper<Scalars['ID']['output']>;
  Int: ResolverTypeWrapper<Scalars['Int']['output']>;
  LaraConfig: ResolverTypeWrapper<GqlLaraConfig>;
  MutateEntryPayload: ResolverTypeWrapper<Omit<GqlMutateEntryPayload, 'day' | 'entry' | 'report'> & { day: GqlResolversTypes['Day'], entry?: Maybe<GqlResolversTypes['Entry']>, report: GqlResolversTypes['Report'] }>;
  Mutation: ResolverTypeWrapper<{}>;
  OAuthPayload: ResolverTypeWrapper<GqlOAuthPayload>;
  PrintPayload: ResolverTypeWrapper<GqlPrintPayload>;
  Query: ResolverTypeWrapper<{}>;
  Report: ResolverTypeWrapper<Report>;
  ReportStatus: GqlReportStatus;
  String: ResolverTypeWrapper<Scalars['String']['output']>;
  Suggestion: ResolverTypeWrapper<GqlSuggestion>;
  Trainee: ResolverTypeWrapper<Trainee>;
  Trainer: ResolverTypeWrapper<Trainer>;
  TrainerTraineePayload: ResolverTypeWrapper<Omit<GqlTrainerTraineePayload, 'trainee' | 'trainer'> & { trainee: GqlResolversTypes['Trainee'], trainer: GqlResolversTypes['Trainer'] }>;
  UpdateCurrentTraineeInput: GqlUpdateCurrentTraineeInput;
  UpdateReportPayload: ResolverTypeWrapper<Omit<GqlUpdateReportPayload, 'report' | 'trainee'> & { report: GqlResolversTypes['Report'], trainee: GqlResolversTypes['Trainee'] }>;
  UpdateTraineeInput: GqlUpdateTraineeInput;
  UpdateTrainerInput: GqlUpdateTrainerInput;
  UserInput: GqlUserInput;
  UserInterface: ResolverTypeWrapper<UserInterface>;
  UserTypeEnum: GqlUserTypeEnum;
}>;

/** Mapping between all available schema types and the resolvers parents */
export type GqlResolversParentTypes = ResolversObject<{
  Admin: GqlAdmin;
  Boolean: Scalars['Boolean']['output'];
  Comment: Comment;
  CommentableInterface: CommentableInterface;
  Company: GqlCompany;
  CreateCommentPayload: Omit<GqlCreateCommentPayload, 'comment' | 'commentable'> & { comment: GqlResolversParentTypes['Comment'], commentable: GqlResolversParentTypes['CommentableInterface'] };
  CreateTraineeInput: GqlCreateTraineeInput;
  CreateTrainerInput: GqlCreateTrainerInput;
  Day: Day;
  DevSetUserPayload: Omit<GqlDevSetUserPayload, 'user'> & { user?: Maybe<GqlResolversParentTypes['UserInterface']> };
  Entry: Entry;
  EntryInput: GqlEntryInput;
  ID: Scalars['ID']['output'];
  Int: Scalars['Int']['output'];
  LaraConfig: GqlLaraConfig;
  MutateEntryPayload: Omit<GqlMutateEntryPayload, 'day' | 'entry' | 'report'> & { day: GqlResolversParentTypes['Day'], entry?: Maybe<GqlResolversParentTypes['Entry']>, report: GqlResolversParentTypes['Report'] };
  Mutation: {};
  OAuthPayload: GqlOAuthPayload;
  PrintPayload: GqlPrintPayload;
  Query: {};
  Report: Report;
  String: Scalars['String']['output'];
  Suggestion: GqlSuggestion;
  Trainee: Trainee;
  Trainer: Trainer;
  TrainerTraineePayload: Omit<GqlTrainerTraineePayload, 'trainee' | 'trainer'> & { trainee: GqlResolversParentTypes['Trainee'], trainer: GqlResolversParentTypes['Trainer'] };
  UpdateCurrentTraineeInput: GqlUpdateCurrentTraineeInput;
  UpdateReportPayload: Omit<GqlUpdateReportPayload, 'report' | 'trainee'> & { report: GqlResolversParentTypes['Report'], trainee: GqlResolversParentTypes['Trainee'] };
  UpdateTraineeInput: GqlUpdateTraineeInput;
  UpdateTrainerInput: GqlUpdateTrainerInput;
  UserInput: GqlUserInput;
  UserInterface: UserInterface;
}>;

export type GqlAdminResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Admin'] = GqlResolversParentTypes['Admin']> = ResolversObject<{
  alexaSkillLinked?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  avatar?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  email?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  firstName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  language?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  lastName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  notification?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  signature?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  theme?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  type?: Resolver<GqlResolversTypes['UserTypeEnum'], ParentType, ContextType>;
  username?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlCommentResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Comment'] = GqlResolversParentTypes['Comment']> = ResolversObject<{
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  text?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  user?: Resolver<GqlResolversTypes['UserInterface'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlCommentableInterfaceResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['CommentableInterface'] = GqlResolversParentTypes['CommentableInterface']> = ResolversObject<{
  __resolveType: TypeResolveFn<'Day' | 'Entry' | 'Report', ParentType, ContextType>;
  comments?: Resolver<Array<GqlResolversTypes['Comment']>, ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
}>;

export type GqlCompanyResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Company'] = GqlResolversParentTypes['Company']> = ResolversObject<{
  id?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  logo?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  name?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlCreateCommentPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['CreateCommentPayload'] = GqlResolversParentTypes['CreateCommentPayload']> = ResolversObject<{
  comment?: Resolver<GqlResolversTypes['Comment'], ParentType, ContextType>;
  commentable?: Resolver<GqlResolversTypes['CommentableInterface'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlDayResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Day'] = GqlResolversParentTypes['Day']> = ResolversObject<{
  comments?: Resolver<Array<GqlResolversTypes['Comment']>, ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  date?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  entries?: Resolver<Array<GqlResolversTypes['Entry']>, ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  status?: Resolver<Maybe<GqlResolversTypes['DayStatusEnum']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlDevSetUserPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['DevSetUserPayload'] = GqlResolversParentTypes['DevSetUserPayload']> = ResolversObject<{
  user?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlEntryResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Entry'] = GqlResolversParentTypes['Entry']> = ResolversObject<{
  comments?: Resolver<Array<GqlResolversTypes['Comment']>, ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  orderId?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  text?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  time?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlLaraConfigResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['LaraConfig'] = GqlResolversParentTypes['LaraConfig']> = ResolversObject<{
  expectedWorkDayMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  finishedWeekDayCount?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  maxEducationDayMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  maxEntryMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  maxPeriodYearsCount?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  maxWorkDayMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  minEducationDayMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  minWorkDayMinutes?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlMutateEntryPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['MutateEntryPayload'] = GqlResolversParentTypes['MutateEntryPayload']> = ResolversObject<{
  day?: Resolver<GqlResolversTypes['Day'], ParentType, ContextType>;
  entry?: Resolver<Maybe<GqlResolversTypes['Entry']>, ParentType, ContextType>;
  report?: Resolver<GqlResolversTypes['Report'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlMutationResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Mutation'] = GqlResolversParentTypes['Mutation']> = ResolversObject<{
  _devloginuser?: Resolver<Maybe<GqlResolversTypes['OAuthPayload']>, ParentType, ContextType, RequireFields<GqlMutation_DevloginuserArgs, 'id'>>;
  _devsetusertype?: Resolver<GqlResolversTypes['DevSetUserPayload'], ParentType, ContextType, RequireFields<GqlMutation_DevsetusertypeArgs, 'type'>>;
  claimTrainee?: Resolver<Maybe<GqlResolversTypes['TrainerTraineePayload']>, ParentType, ContextType, RequireFields<GqlMutationClaimTraineeArgs, 'id'>>;
  createCommentOnDay?: Resolver<GqlResolversTypes['CreateCommentPayload'], ParentType, ContextType, RequireFields<GqlMutationCreateCommentOnDayArgs, 'id' | 'text' | 'traineeId'>>;
  createCommentOnEntry?: Resolver<GqlResolversTypes['CreateCommentPayload'], ParentType, ContextType, RequireFields<GqlMutationCreateCommentOnEntryArgs, 'id' | 'text' | 'traineeId'>>;
  createCommentOnReport?: Resolver<GqlResolversTypes['CreateCommentPayload'], ParentType, ContextType, RequireFields<GqlMutationCreateCommentOnReportArgs, 'id' | 'text' | 'traineeId'>>;
  createEntry?: Resolver<GqlResolversTypes['MutateEntryPayload'], ParentType, ContextType, RequireFields<GqlMutationCreateEntryArgs, 'dayId' | 'input'>>;
  createOAuthCode?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  createTrainee?: Resolver<Maybe<GqlResolversTypes['Trainee']>, ParentType, ContextType, RequireFields<GqlMutationCreateTraineeArgs, 'input'>>;
  createTrainer?: Resolver<Maybe<GqlResolversTypes['Trainer']>, ParentType, ContextType, RequireFields<GqlMutationCreateTrainerArgs, 'input'>>;
  deleteEntry?: Resolver<GqlResolversTypes['MutateEntryPayload'], ParentType, ContextType, RequireFields<GqlMutationDeleteEntryArgs, 'id'>>;
  linkAlexa?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType, RequireFields<GqlMutationLinkAlexaArgs, 'code' | 'state'>>;
  login?: Resolver<Maybe<GqlResolversTypes['OAuthPayload']>, ParentType, ContextType, RequireFields<GqlMutationLoginArgs, 'email'>>;
  markUserForDeletion?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType, RequireFields<GqlMutationMarkUserForDeletionArgs, 'id'>>;
  unclaimTrainee?: Resolver<Maybe<GqlResolversTypes['TrainerTraineePayload']>, ParentType, ContextType, RequireFields<GqlMutationUnclaimTraineeArgs, 'id'>>;
  unlinkAlexa?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType>;
  unmarkUserForDeletion?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType, RequireFields<GqlMutationUnmarkUserForDeletionArgs, 'id'>>;
  updateCurrentTrainee?: Resolver<Maybe<GqlResolversTypes['Trainee']>, ParentType, ContextType, RequireFields<GqlMutationUpdateCurrentTraineeArgs, 'input'>>;
  updateCurrentUser?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType, Partial<GqlMutationUpdateCurrentUserArgs>>;
  updateDay?: Resolver<Maybe<GqlResolversTypes['Day']>, ParentType, ContextType, RequireFields<GqlMutationUpdateDayArgs, 'id'>>;
  updateEntry?: Resolver<GqlResolversTypes['MutateEntryPayload'], ParentType, ContextType, RequireFields<GqlMutationUpdateEntryArgs, 'id' | 'input'>>;
  updateEntryOrder?: Resolver<GqlResolversTypes['MutateEntryPayload'], ParentType, ContextType, RequireFields<GqlMutationUpdateEntryOrderArgs, 'dayId' | 'entryId' | 'orderId'>>;
  updateReport?: Resolver<Maybe<GqlResolversTypes['UpdateReportPayload']>, ParentType, ContextType, RequireFields<GqlMutationUpdateReportArgs, 'id'>>;
  updateTrainee?: Resolver<Maybe<GqlResolversTypes['Trainee']>, ParentType, ContextType, RequireFields<GqlMutationUpdateTraineeArgs, 'id' | 'input'>>;
  updateTrainer?: Resolver<Maybe<GqlResolversTypes['Trainer']>, ParentType, ContextType, RequireFields<GqlMutationUpdateTrainerArgs, 'id' | 'input'>>;
}>;

export type GqlOAuthPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['OAuthPayload'] = GqlResolversParentTypes['OAuthPayload']> = ResolversObject<{
  accessToken?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  expiresIn?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  refreshToken?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlPrintPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['PrintPayload'] = GqlResolversParentTypes['PrintPayload']> = ResolversObject<{
  estimatedWaitingTime?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlQueryResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Query'] = GqlResolversParentTypes['Query']> = ResolversObject<{
  alexaLinkingUrl?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  cleanup?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  companies?: Resolver<Maybe<Array<GqlResolversTypes['Company']>>, ParentType, ContextType>;
  config?: Resolver<GqlResolversTypes['LaraConfig'], ParentType, ContextType>;
  currentUser?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType>;
  getUser?: Resolver<Maybe<GqlResolversTypes['UserInterface']>, ParentType, ContextType, RequireFields<GqlQueryGetUserArgs, 'id'>>;
  print?: Resolver<GqlResolversTypes['PrintPayload'], ParentType, ContextType, RequireFields<GqlQueryPrintArgs, 'ids'>>;
  reportForTrainee?: Resolver<Maybe<GqlResolversTypes['Report']>, ParentType, ContextType, RequireFields<GqlQueryReportForTraineeArgs, 'id' | 'week' | 'year'>>;
  reportForYearAndWeek?: Resolver<Maybe<GqlResolversTypes['Report']>, ParentType, ContextType, RequireFields<GqlQueryReportForYearAndWeekArgs, 'week' | 'year'>>;
  reports?: Resolver<Array<Maybe<GqlResolversTypes['Report']>>, ParentType, ContextType, Partial<GqlQueryReportsArgs>>;
  suggestions?: Resolver<Array<GqlResolversTypes['Suggestion']>, ParentType, ContextType>;
  trainees?: Resolver<Array<GqlResolversTypes['Trainee']>, ParentType, ContextType>;
  trainers?: Resolver<Array<GqlResolversTypes['Trainer']>, ParentType, ContextType>;
}>;

export type GqlReportResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Report'] = GqlResolversParentTypes['Report']> = ResolversObject<{
  comments?: Resolver<Array<GqlResolversTypes['Comment']>, ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  days?: Resolver<Array<GqlResolversTypes['Day']>, ParentType, ContextType>;
  department?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  nextReportLink?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  previousReportLink?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  reportAccepted?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  status?: Resolver<GqlResolversTypes['ReportStatus'], ParentType, ContextType>;
  summary?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  week?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  year?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlSuggestionResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Suggestion'] = GqlResolversParentTypes['Suggestion']> = ResolversObject<{
  text?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  time?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlTraineeResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Trainee'] = GqlResolversParentTypes['Trainee']> = ResolversObject<{
  alexaSkillLinked?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  avatar?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  company?: Resolver<GqlResolversTypes['Company'], ParentType, ContextType>;
  course?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  deleteAt?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  email?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  endDate?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  endOfToolUsage?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  firstName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  language?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  lastName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  notification?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  openReportsCount?: Resolver<GqlResolversTypes['Int'], ParentType, ContextType>;
  reports?: Resolver<Array<GqlResolversTypes['Report']>, ParentType, ContextType>;
  signature?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  startDate?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  startOfToolUsage?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  theme?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  trainer?: Resolver<Maybe<GqlResolversTypes['Trainer']>, ParentType, ContextType>;
  type?: Resolver<GqlResolversTypes['UserTypeEnum'], ParentType, ContextType>;
  username?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlTrainerResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['Trainer'] = GqlResolversParentTypes['Trainer']> = ResolversObject<{
  alexaSkillLinked?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  avatar?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  deleteAt?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  email?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  firstName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  language?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  lastName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  notification?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  signature?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  theme?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  trainees?: Resolver<Array<GqlResolversTypes['Trainee']>, ParentType, ContextType>;
  type?: Resolver<GqlResolversTypes['UserTypeEnum'], ParentType, ContextType>;
  username?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlTrainerTraineePayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['TrainerTraineePayload'] = GqlResolversParentTypes['TrainerTraineePayload']> = ResolversObject<{
  trainee?: Resolver<GqlResolversTypes['Trainee'], ParentType, ContextType>;
  trainer?: Resolver<GqlResolversTypes['Trainer'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlUpdateReportPayloadResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['UpdateReportPayload'] = GqlResolversParentTypes['UpdateReportPayload']> = ResolversObject<{
  report?: Resolver<GqlResolversTypes['Report'], ParentType, ContextType>;
  trainee?: Resolver<GqlResolversTypes['Trainee'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlUserInterfaceResolvers<ContextType = Context, ParentType extends GqlResolversParentTypes['UserInterface'] = GqlResolversParentTypes['UserInterface']> = ResolversObject<{
  __resolveType: TypeResolveFn<'Admin' | 'Trainee' | 'Trainer', ParentType, ContextType>;
  alexaSkillLinked?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  avatar?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  createdAt?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  email?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  firstName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['ID'], ParentType, ContextType>;
  language?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  lastName?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  notification?: Resolver<Maybe<GqlResolversTypes['Boolean']>, ParentType, ContextType>;
  signature?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  theme?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  type?: Resolver<GqlResolversTypes['UserTypeEnum'], ParentType, ContextType>;
  username?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
}>;

export type GqlResolvers<ContextType = Context> = ResolversObject<{
  Admin?: GqlAdminResolvers<ContextType>;
  Comment?: GqlCommentResolvers<ContextType>;
  CommentableInterface?: GqlCommentableInterfaceResolvers<ContextType>;
  Company?: GqlCompanyResolvers<ContextType>;
  CreateCommentPayload?: GqlCreateCommentPayloadResolvers<ContextType>;
  Day?: GqlDayResolvers<ContextType>;
  DevSetUserPayload?: GqlDevSetUserPayloadResolvers<ContextType>;
  Entry?: GqlEntryResolvers<ContextType>;
  LaraConfig?: GqlLaraConfigResolvers<ContextType>;
  MutateEntryPayload?: GqlMutateEntryPayloadResolvers<ContextType>;
  Mutation?: GqlMutationResolvers<ContextType>;
  OAuthPayload?: GqlOAuthPayloadResolvers<ContextType>;
  PrintPayload?: GqlPrintPayloadResolvers<ContextType>;
  Query?: GqlQueryResolvers<ContextType>;
  Report?: GqlReportResolvers<ContextType>;
  Suggestion?: GqlSuggestionResolvers<ContextType>;
  Trainee?: GqlTraineeResolvers<ContextType>;
  Trainer?: GqlTrainerResolvers<ContextType>;
  TrainerTraineePayload?: GqlTrainerTraineePayloadResolvers<ContextType>;
  UpdateReportPayload?: GqlUpdateReportPayloadResolvers<ContextType>;
  UserInterface?: GqlUserInterfaceResolvers<ContextType>;
}>;

