########################################################
# Reusable build workflow                              #
########################################################
name: build

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      debug:
        required: true
        type: string
      mode:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-job
    environment: ${{ inputs.environmentName }}
    env:
      DEBUG: ${{ inputs.debug }}
      MODE: ${{ inputs.mode }}
      AUTH_HEADER: ${{ secrets.AUTH_HEADER }}
      MICROSOFT_TENANT_ID: ${{ secrets.MICROSOFT_TENANT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      SUPPORT_MAIL: ${{ secrets.SUPPORT_MAIL }}
      URL_ORIGIN: ${{ secrets.URL_ORIGIN }}
      COMPANY_ABBREVIATION: ${{ secrets.COMPANY_ABBREVIATION }}
      OLD_COMPANY_NAME: ${{ secrets.OLD_COMPANY_NAME }}
      NEW_COMPANY_NAME: ${{ secrets.NEW_COMPANY_NAME }}
      AVATAR_URL: ${{ secrets.AVATAR_URL }}
      LARA_VERSION: ${{ github.ref_name }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
            .yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-in-${{ github.ref_name }}

      ##############
      - name: Compile and build
        run: yarn clean && yarn compile && yarn build

      - name: Upload dist and lib
        uses: actions/upload-artifact@v4
        with:
          name: dist-and-lib
          path: |
            packages/*/dist
            packages/*/lib
