########################################################
# Reusable install workflow                            #
########################################################
name: install

on:
  workflow_call:

jobs:
  install:
    name: install-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            .yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-in-${{ github.ref_name }}
      - run: yarn --cache-folder .yarn
